### PR TITLE
Adding a new file to the rep under a new branch

### PR DESCRIPTION
**Pull request by darthsalad**

### CODE REVIEW

**Comment by LearningMonkey61** [comment]
@DarthSalad Name not added to `CONTRIBUTERS.md`, Make a new commit and make a pull request again.

**Comment by darthsalad** [comment]
I pushed the committed forked repo, but I can't seem to make a new pull request.

**Comment by LearningMonkey61** [comment]
@DarthSalad Done. If your pull request is open you can continue committing more code. The changes will be reflected here.

**Comment by darthsalad** [comment]
Thanks bhaiya :D

**Pull request merged**
